#!/bin/bash

set -euo pipefail

OPTS=( "-e" "PYTHON=python3" )
if [ -n "${DEBUG:-}" ]; then
    set -x
    OPTS+=( -e DEBUG="${DEBUG}" )
fi

if [ $# -eq 0 ]; then
    examples="pydeep terasort"
else
    examples=$@
fi

for e in ${examples}; do
    cmd="source /etc/profile && cd /examples/${e} && ./run_tests && ./run"
    docker exec "${OPTS[@]}" pydoop bash -c "${cmd}"
done
