#!/usr/bin/env bash

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x
this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)
. "${this_dir}/../config.sh"
. "${this_dir}/common.sh"

[ ${PY_VER} -le 2 ] && die "ERROR: Python 3 required"

pushd "${this_dir}"
${HDFS} dfs -test -d "${BNECKS_DIR}" || ./run_genbnecks
${HDFS} dfs -rm -r -f "${TRAINED_MODELS_DIR}" "${TEST_OUTPUT_DIR}"
${PYTHON} retrain_subsets.py --num-steps "${NUM_STEPS}" --num-maps "${RETRAIN_NUM_MAPS}" --log-level "${LOG_LEVEL}" "${BNECKS_DIR}" "${TRAINED_MODELS_DIR}"
${PYTHON} plot_training.py "${TRAINED_MODELS_DIR}" "${PLOTS_DIR}"
${PYTHON} test_subsets.py --bnecks-dir "${BNECKS_DIR}" --num-maps "${TEST_NUM_MAPS}" --log-level "${LOG_LEVEL}" "${TRAINED_MODELS_DIR}" "${TEST_OUTPUT_DIR}"
${HDFS} dfs -ls -C "${TEST_OUTPUT_DIR}" | grep -E 'part-m-[0-9]+$' | xargs ${HDFS} dfs -cat | sort
./run_dump_weights
popd
