#!/usr/bin/env bash

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x
this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)
. "${this_dir}/../config.sh"
. "${this_dir}/common.sh"

[ ${PY_VER} -le 2 ] && die "ERROR: Python 3 required"

CMP_INPUT_DIR="cmp_input"

pushd "${this_dir}"
${HDFS} dfs -test -d "${TRAINED_MODELS_DIR}" || die "models dir not found"
${HDFS} dfs -rm -r -f "${CMP_INPUT_DIR}"
${HDFS} dfs -mkdir "${CMP_INPUT_DIR}"
${HDFS} dfs -cp "${TRAINED_MODELS_DIR}"/'*.zip' "${CMP_INPUT_DIR}"
${HDFS} dfs -rm -r -f "${CMP_OUTPUT_DIR}"
${PYTHON} compare_models.py --bnecks-dir "${BNECKS_DIR}" --num-maps "${CMP_NUM_MAPS}" --log-level "${LOG_LEVEL}" "${CMP_INPUT_DIR}" "${CMP_OUTPUT_DIR}"
popd
