#!/usr/bin/env bash

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x
this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)
. "${this_dir}/../config.sh"
. "${this_dir}/common.sh"

[ ${PY_VER} -le 2 ] && die "ERROR: Python 3 required"

pushd "${this_dir}"
${HDFS} dfs -test -d "${CMP_INPUT_DIR}" || die "input dir not found"
${HDFS} dfs -rm -r -f "${CMP_OUTPUT_DIR}"
${PYTHON} compare_models.py --num-maps "${CMP_NUM_MAPS}" --log-level "${LOG_LEVEL}" "${CMP_INPUT_DIR}" "${CMP_OUTPUT_DIR}"
popd
