#!/usr/bin/env bash

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x
this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)
. "${this_dir}/../config.sh"

[ ${PY_VER} -le 2 ] && die "ERROR: Python 3 required"

[ -n "${DEBUG:-}" ] && OPTS="-v" || OPTS=""

pushd "${this_dir}"
# doctest is REALLY verbose. Do not pass OPTS
${PYTHON} -m doctest pydeep/*.py
export PYTHONPATH="${this_dir}:${PYTHONPATH:-}"
pushd "${this_dir}/test"
${PYTHON} -m unittest ${OPTS:-} "$@"
popd
popd
